spring:
  bundesbank:
    url-template: "https://www.bundesbank.de/statistic-rmi/StatisticDownload?tsId=BBEX3.D.{currency}.EUR.BB.AC.000&mode=its&its_fileFormat=sdmx&its_dateFormat=default"
    currencies:
      - AUD
      - BGN
      - BRL
      - CAD
      - CYP
      - TRY