spring:
  bundesbank:
    url-template: "https://www.bundesbank.de/statistic-rmi/StatisticDownload?tsId=BBEX3.D.{currency}.EUR.BB.AC.000&mode=its&its_fileFormat=sdmx&its_dateFormat=default"
    currencies:
      - AUD
      - BGN
      - BRL
      - CAD
      - CHF
      - CNY
      - CYP
      - CZK
      - DKK
      - EEK
      - GBP
      - GRD
      - HKD
      - HRK
      - HUF
      - IDR
      - ILS
      - INR
      - ISK
      - JPY
      - KRW
      - LTL
      - LVL
      - MTL
      - MXN
      - MYR
      - NOK
      - NZD
      - PHP
      - PLN
      - ROL
      - RON
      - RUB
      - SEK
      - SGD
      - SIT
      - SKK
      - THB
      - TRL
      - TRY
      - USD
      - ZAR